spring:
  profiles:
    active: dev
server:
  port: 8083

---

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: test
  jpa:
    show_sql: false
    database: H2
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  h2:
    console:
      enabled: true
      path: "/h2-console"


---

#spring:
#  profiles: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/smartq?serverTimezone=UTC
#    username: root
#    password: babatunde2
#  jpa:
#    show_sql: true
#    database: MYSQL
#    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management